development:
  adapter: postgresql
  encoding: unicode
  database: couch_potato_app_development
  pool: 2
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST']
  database: production